env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
    flowVersion: '0.53'
  propWrapperFunctions:
    - forbidExtraProps
    - property: freeze
      object: Object
    - property: myFavoriteWrapper
  componentWrapperFunctions:
    - observer
    - property: styled
    - property: observer
      object: Mobx
    - property: observer
      object: "<pragma>"
  linkComponents:
    - Hyperlink
    - name: Link
      linkAttribute: to
rules:
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/prop-types: off
